# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20151223_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='name',
        ),
        migrations.AddField(
            model_name='track',
            name='link',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
    ]
